Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "node01"]
 end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
 end

  # fix message "stdin: is not tty"
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
 end

  # add swap
  config.vm.provision :shell, inline: "fallocate -l 4G /swapfile && chmod 0600 /swapfile && mkswap /swapfile && swapon /swapfile && echo '/swapfile none swap sw 0 0' >> /etc/fstab"
  config.vm.provision :shell, inline: "echo vm.swappiness = 10 >> /etc/sysctl.conf && echo vm.vfs_cache_pressure = 50 >> /etc/sysctl.conf && sysctl -p"

  # run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose        = true # logging level (false=minimal; true=v; vvv; vvvv)
    ansible.install        = true # install or not ansible
#    ansible.limit          = "all" # or only "nodes" group, etc.
#    ansible.provisioning_path = # ansible file directory default is /vagrant
#    ansible.inventory_path = "inventory" # affected hosts(nodes) 
 end

end
