Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.customize ["modifyvm", :id, "--name", "node01"]
 end
  # Run Ansible from the Vagrant VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose        = true # logging level (false=minimal; true=v; vvv; vvvv)
    ansible.install        = true # install or not ansible
#    ansible.limit          = "all" # or only "nodes" group, etc.
#    ansible.provisioning_path = # ansible file directory default is /vagrant
#    ansible.inventory_path = "inventory" # affected hosts(nodes) 
 end
end
